### ISSUE TITLE
Could you please provide the original network dataset?

### ISSUE THREAD

**Issue by scottshufe** [EnderGed/Fairwalk#1]
Thanks for your excellent work!
Could you please provide me with the original network datasets (LA & London) in the article?

**Comment by scottshufe** [comment]
Thanks for your excellent work!
Could you please provide the original network dataset in the article for me?

**Comment by EnderGed** [comment]
Thank you for the kind words.
Unfortunately, due to our institute's data regulations we cannot share the dataset.
I can only suggest using Movielens, as it's a public network with attributes and from other researchers we know that Fairwalk performs well on it.
